# inference 

python3 data_augmentation.py --TargetClassPath_Image DiffSeg_Data/VOC_Multi_Attention_bird_GPT3/train_image --TargetClassPath_Mask DiffSeg_Data/VOC_Multi_Attention_bird_GPT3/refine_gt_crf --OtherClassPath DiffSeg_Data/VOC_Multi_Attention_MAP_300 --OutputPath DiffSeg_Data/Augmentation_One